name: vocal_message
description: record vocals, upload them on azure blob and download replies
version: 0.0.5

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.5"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.0 
  just_audio: ^0.9.40 #0.9.31 #^0.9.31  #0.9.11     ^0.9.37 Command CompileSwiftSources failed with a nonzero exit code
  just_audio_windows: any
  audioplayers: ^6.1.0 
  # if you do to have XCode 15 stick to audioplayers : 5.2.1
  # else error: cannot find 'AVURLAssetOverrideMIMETypeKey' in scope
  font_awesome_flutter: ^10.1.0
  record: ^5.0.5 
  flutter_vibrate: ^1.1.0
  lottie: ^3.1.0 #1.2.1
  xml: ^6.2.2
  connectivity_plus: ^6.0.2 #^5.0.2 #4.0.2
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^1.0.0 