name: bibliophone
description: Record audio send it to your azure cloud and perform
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.5"

dependencies:
  flutter:
    sdk: flutter
  # edit transcription
  re_editor: ^0.3.0
  
  path_provider: ^2.1.3
  intl: ^0.19.0
  permission_handler: ^11.3.0 
  
  # audio
  record: ^5.0.5 

  just_audio: ^0.9.40 #0.9.31 #^0.9.31  #0.9.11     ^0.9.37 Command CompileSwiftSources failed with a nonzero exit code
  just_audio_windows: any
  just_audio_mpv: any
  audioplayers: ^6.1.0
  # on macos if you do not to have XCode 15 or above pass your way
  # .pub-cache/hosted/pub.dev/audioplayers_darwin-6.0.0/macos/Classes/WrappedMediaPlayer.swift:185:37: error: cannot find 'AVURLAssetOverrideMIMETypeKey' in scope
  # macos mic permission might not work anyway..

  go_router: ^14.2.8
  font_awesome_flutter: ^10.1.0
  flutter_vibrate: ^1.1.0
  lottie: ^3.1.0 #1.2.1
  xml: ^6.2.2
  connectivity_plus: ^6.0.2 #^5.0.2 #4.0.2
  internet_connection_checker: ^1.0.0+1
  device_info_plus: ^10.1.2
  package_info_plus: ^8.0.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/dustbin.json
    - assets/dustbin_grey.json
    #- assets/sherpa-onnx-streaming-zipformer-fr-2023-04-14/